file_type: markdown                                       # options: markdown, pdf, txt
embedding_type: openai                                    # options: openai, other_embedding_service


documentloader:
  # file_path: "/home/peet/dev/azure-docs-md/"            # absolute nix
  # file_path: "G:\\dev\\azure-docs\\"                      # absolute win
  file_path: "files/"                                     # relative
  # file_path: 'G:\\dev\\azure-docs\\articles\\deployment-environments\\'
  max_workers: 140
  project: https://github.com/MicrosoftDocs/azure-docs/    # we generate a source metadata from project+location
  version: "tree/main/"

splitter:
  tokensplitter:
    max_token_seq_len: 400
    token_overlap: 100

embedder:
  embedderapi:
    host: localhost
    port: 80
  # embedding_model: "text-embedding-3-small"             #options: https://platform.openai.com/docs/guides/embeddings/
  embedding_model: "dunzhang/stella_en_1.5B_v5"
  batch_size: 6000 
  openai:
    batch_size: 2048
    max_tokens_per_minute: 150000                         # TPM: error: on tokens per min (TPM): Limit 150000, Requested 172752. 
    max_requests_per_minute: 3000                         # RPM: 3,000 
    batch_queue_limit: 3000000                            # Batch Queue Limit: 3,000,000
  sentencetransformer:
    batch_size: 2

# chroma:
#   url: chroma.d3eyekfegubub9fz.switzerlandnorth.azurecontainer.io
#   port: 8000
#   tenant: default_tenant
#   database: default_database
#   collection: openai

pinecone:
  index_name: discovery
  index_host_suffix: 226a147.svc.aped-4627-b74a.pinecone.io
  namespace: newvnettest
